version: '3.9'
services:
  db:
    env_file:
      - .env.test
  api:
    env_file:
      - .env.test
    image: vineyard-api:test
    build: null
    environment:
      ASPNETCORE_ENVIRONMENT: Test
  frontend:
    env_file:
      - .env.test
    image: vineyard-frontend:test
    build: null
